import { Skill, SkillCategory, SkillCategoryOption } from "@/types";

export const SKILLS: Skill[] = [
  {
    id: "html-css",
    name: "HTML/CSS",
    level: 80,
    category: "frontend",
    yearsOfExperience: 2,
    context: "Semantic HTML, Flexbox/Grid, responsive design fundamentals",
    highlights: ["Responsive layouts", "CSS animations", "BEM methodology"],
  },
  {
    id: "javascript",
    name: "JavaScript ES6+",
    level: 70,
    category: "frontend",
    yearsOfExperience: 2,
    context: "Solid foundation in modern JavaScript, async patterns",
    highlights: ["Array methods", "Async/await", "ES6 features"],
  },
  {
    id: "react",
    name: "React",
    level: 75,
    category: "frontend",
    yearsOfExperience: 1.5,
    context:
      "Built microfrontend components for financial applications at NN Insurance",
    highlights: [
      "Hooks (useState, useEffect, custom)",
      "Component patterns",
      "Performance basics",
    ],
  },
  {
    id: "typescript",
    name: "TypeScript",
    level: 65,
    category: "frontend",
    yearsOfExperience: 1.5,
    context: "Production experience with typed React components",
    highlights: ["Type definitions", "Interfaces", "Props typing"],
  },
  {
    id: "redux",
    name: "Redux Toolkit",
    level: 70,
    category: "frontend",
    yearsOfExperience: 1.5,
    context: "State management for insurance quote flows and multi-step forms",
    highlights: ["Slices & reducers", "RTK Query basics", "Redux Thunk"],
  },
  {
    id: "mui",
    name: "Material-UI",
    level: 75,
    category: "frontend",
    yearsOfExperience: 1.5,
    context: "Custom MUI component library for enterprise apps",
    highlights: ["Component customization", "Theme usage", "Form components"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    level: 60,
    category: "frontend",
    yearsOfExperience: 0.5,
    context: "Utility-first CSS for personal projects and prototyping",
    highlights: [
      "Responsive utilities",
      "Custom configurations",
      "Component styling",
    ],
  },
  {
    id: "yup",
    name: "Yup / React Hook Form",
    level: 70,
    category: "frontend",
    yearsOfExperience: 1.5,
    context: "Form validation for complex insurance quotation forms",
    highlights: ["Schema validation", "Custom validators", "Error handling"],
  },
  {
    id: "git",
    name: "Git/GitHub",
    level: 75,
    category: "tools",
    yearsOfExperience: 2,
    context: "Version control, branching, code reviews in team environment",
    highlights: ["Feature branches", "Pull requests", "Conflict resolution"],
  },
  {
    id: "jest",
    name: "Jest",
    level: 40,
    category: "tools",
    yearsOfExperience: 1.5,
    context: "Unit testing React components, maintained test coverage",
    highlights: ["Component testing", "Mock functions", "Test coverage"],
  },
  {
    id: "azure",
    name: "Azure DevOps",
    level: 65,
    category: "tools",
    yearsOfExperience: 1.5,
    context: "Agile workflow, sprint planning, CI/CD pipelines",
    highlights: ["Work items", "Boards", "Basic pipelines"],
  },
  {
    id: "figma",
    name: "Figma",
    level: 65,
    category: "tools",
    yearsOfExperience: 1,
    context: "Design handoff, component specs, collaboration with UI/UX team",
    highlights: ["Design inspection", "Asset export", "Developer mode"],
  },
  {
    id: "vscode",
    name: "VS Code",
    level: 75,
    category: "tools",
    yearsOfExperience: 2,
    context: "Daily driver with productivity extensions",
    highlights: ["Extensions", "Shortcuts", "Debugging tools"],
  },
  {
    id: "nodejs",
    name: "Node.js",
    level: 15,
    category: "backend",
    yearsOfExperience: 0.5,
    context:
      "Learning backend fundamentals through IBM Full Stack certification",
    highlights: ["REST API basics", "npm packages", "Backend fundamentals"],
  },
  {
    id: "express",
    name: "Express",
    level: 15,
    category: "backend",
    yearsOfExperience: 0.5,
    context: "Building simple APIs for personal projects",
    highlights: ["Routing", "Middleware basics", "Error handling"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    level: 15,
    category: "backend",
    yearsOfExperience: 0.5,
    context: "NoSQL database for learning projects",
    highlights: ["CRUD operations", "Schema design", "Mongoose basics"],
  },
  {
    id: "docker",
    name: "Docker",
    level: 15,
    category: "tools",
    yearsOfExperience: 0.5,
    context: "Basic containerization for development environments",
    highlights: ["Docker basics", "Compose files", "Container usage"],
  },
];

const CATEGORY_LABELS: Record<SkillCategory, string> = {
  frontend: "Frontend",
  backend: "Backend",
  tools: "Tools",
};

export const SKILL_CATEGORIES: SkillCategoryOption[] = [
  { id: "all", label: "All", count: SKILLS.length },
  ...Object.entries(CATEGORY_LABELS).map(([key, label]) => ({
    id: key as SkillCategory,
    label,
    count: SKILLS.filter((s) => s.category === key).length,
  })),
];
